# Site parameters
Title = "nopatch.me" # Title of your site
Description = "" # Description for your site
PreviewLength = 30 # Length of the post preview in the index (number of words)
PostsPerPage = 4

# Disqus parameters
DisqusShortname = "nopatch"

# Google Analytics
GoogleAnalyticsID = "UA-93249230-1"

# Directories
Posts = "posts" # Directory containing the posts
Templates = "templates" # Directory containing the templates
Public = "static" # Directory where the generated static site will be stored
