# Site parameters
Title = "zlowram's blog" # Title of your site
Description = "Yet another blog of another infosec enthusiast. CTFs, reversing, exploiting, coding and more." # Description for your site
Keywords = "hacking, CTF, write-up, exploiting, reversing"
PreviewLength = 30 # Length of the post preview in the index (number of words)
PostsPerPage = 4

# Disqus parameters
DisqusShortname = "nopatch"

# Google Analytics
GoogleAnalyticsID = "UA-93249230-1"

# Directories
Posts = "posts" # Directory containing the posts
Templates = "templates" # Directory containing the templates
Public = "static" # Directory where the generated static site will be stored
